#!/bin/bash -e

for x in mvn spark-submit ; do
    if [ -z `which $x` ]; then
      echo "$x must be on the path"
      exit 1
    fi
done

(cd data; ./download-all-symbols.sh)

mvn clean package

spark-submit  --class com.cloudera.datascience.risk.RunRisk target/ch09-risk-1.0.2-jar-with-dependencies.jar .
